server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: message-request-consumer-1

topics:
  message:
    request:
      topic: "message.request.topic.v1"